server:
  port: 9001
spring:
  datasource:
    username:
    password:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host:
      port: 6379
      database: 0
      password: 1234

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    #operations-sorter: order
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: 'com.pg'
      paths-to-match: '/**'
  default-flat-param-object: true
  packages-to-scan: com.pg.backend